var searchData=
[
  ['makeevents',['makeEvents',['../classamimodel.html#a4d4b20c81af6d7ed977b6b818c7b22db',1,'amimodel']]],
  ['makesyms',['makeSyms',['../classamimodel.html#a5aba9155145df4b3f70bfec887c25af9',1,'amimodel']]],
  ['max',['max',['../namespaceamici.html#a98d705fa2f3a5e7566f99fc26d1573de',1,'amici']]],
  ['mexfunction',['mexFunction',['../interface__matlab_8cpp.html#a6a215cbfde54f82a3ce599228fc3fce5',1,'interface_matlab.cpp']]],
  ['min',['min',['../namespaceamici.html#a0e1665a05c4dfee1572bea48f7930502',1,'amici']]],
  ['minus',['minus',['../classamici_1_1_ami_vector.html#a19ad39a609bfc430ed6f7992e841b024',1,'amici::AmiVector']]],
  ['model',['Model',['../classamici_1_1_model.html#a30c57abda5ed227c85b50007cee876db',1,'amici::Model::Model()'],['../classamici_1_1_model.html#abd567a1612a8b947ca43c74df3b83273',1,'amici::Model::Model(const int nx_rdata, const int nxtrue_rdata, const int nx_solver, const int nxtrue_solver, const int ny, const int nytrue, const int nz, const int nztrue, const int ne, const int nJ, const int nw, const int ndwdx, const int ndwdp, const int nnz, const int ubw, const int lbw, amici::SecondOrderMode o2mode, const std::vector&lt; amici::realtype &gt; &amp;p, std::vector&lt; amici::realtype &gt; k, const std::vector&lt; int &gt; &amp;plist, std::vector&lt; amici::realtype &gt; idlist, std::vector&lt; int &gt; z2event)']]],
  ['model_5fdae',['Model_DAE',['../classamici_1_1_model___d_a_e.html#a7d20f16a3b4deb14a32fc24b2552f493',1,'amici::Model_DAE::Model_DAE()'],['../classamici_1_1_model___d_a_e.html#a9c21398a0bdb7e31b88e181835a8ff7b',1,'amici::Model_DAE::Model_DAE(const int nx_rdata, const int nxtrue_rdata, const int nx_solver, const int nxtrue_solver, const int ny, const int nytrue, const int nz, const int nztrue, const int ne, const int nJ, const int nw, const int ndwdx, const int ndwdp, const int nnz, const int ubw, const int lbw, const SecondOrderMode o2mode, std::vector&lt; realtype &gt; const &amp;p, std::vector&lt; realtype &gt; const &amp;k, std::vector&lt; int &gt; const &amp;plist, std::vector&lt; realtype &gt; const &amp;idlist, std::vector&lt; int &gt; const &amp;z2event)']]],
  ['model_5fode',['Model_ODE',['../classamici_1_1_model___o_d_e.html#ac1e4d80aa9b64e27e48c740d27b1d907',1,'amici::Model_ODE::Model_ODE()'],['../classamici_1_1_model___o_d_e.html#ad79df95dc03f27d06c0e89f290bfa08a',1,'amici::Model_ODE::Model_ODE(const int nx_rdata, const int nxtrue_rdata, const int nx_solver, const int nxtrue_solver, const int ny, const int nytrue, const int nz, const int nztrue, const int ne, const int nJ, const int nw, const int ndwdx, const int ndwdp, const int nnz, const int ubw, const int lbw, const SecondOrderMode o2mode, std::vector&lt; realtype &gt; const &amp;p, std::vector&lt; realtype &gt; const &amp;k, std::vector&lt; int &gt; const &amp;plist, std::vector&lt; realtype &gt; const &amp;idlist, std::vector&lt; int &gt; const &amp;z2event)']]],
  ['mxarraytovector',['mxArrayToVector',['../namespaceamici.html#af8f91dbb6a395a9907c59dd92991ec18',1,'amici']]]
];
